### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by pas2al** [pablodenadai/angular2-seed-project#81]
What is the plan for this project? I mean if it is deprecated, we can delete it. Would it be useful to anyone if the code base is deprecated? Not really. I would suggest we make it up to date and add some new ideas to it to provide people a good angular2 example application or we remove it, because it will be way more confusing than helpful. What do you think?

**Comment by pablodenadai** [comment]
Hey mate. At this stage I'm not thinking of removing the project from GitHub. I don't like deleting history and it also serves as a bit of a portfolio to myself. 

I have however, made clear that the project is deprecated. I've added a message to both header and README file.

That said, if anyone decides to bring the project up-to-date (eg rc1) I'd be more than happy to review and merge the PR.

**Comment by pas2al** [comment]
Hi mate,
sure, i agree on keeping history. But for me it feels a bit strange to see the "deprecated" notice in the project description (header). Everyone sees on the first glimpse that the project is deprecated (and i wouldn't click on that). What do you think of removing the notice from the project description and we make it clear in the README file. I would add some lines to make it more clear and ask for contribution ;-). Besides of this our own profiles would like a little bit better with a project contributed to which is useful and not just some kind of archive.

It doesn't look that nice:

![ohne titel](https://cloud.githubusercontent.com/assets/14128066/16087755/69cf0082-3324-11e6-945f-ac38dc2fc2a8.png)

What do you mean? @ghpabs
